### ISSUE TITLE
Ability to print hosts based on filters

### ISSUE THREAD

**Issue by defektive** [analog-substance/arsenic#15]
It'd be nice to list out host info based on filters.

- Print URLs of hosts with web ports open `arsenic hosts -q 'in flags webports' -urls | aquatone`
- Print json of hosts in CIDr `arsenic hosts -q 'eq cidr 10.0.0.1/12' -json | jq`

I think initially we can just dump JSON for all the hosts and use `jq` for filtering. Then we'll have a decent idea of what filters we can bundle in.

**Comment by defektive** [comment]
Depending on how this turns out, it might be nice to be able to flag based on these queries.

```bash
arsenic hosts -q 'in ports 2122' -f vuln-service # add flag
arsenic hosts -u # update all flags
```

though that would make the `flags` command obsolete an #14

**Comment by NoF0rte** [comment]
`arsenic hosts`
- [ ] Be able to create new host
