### ISSUE TITLE
Discovery scan reverse lookups not being added to any file that is scanned by recon

### ISSUE THREAD

**Issue by T3rm1nal23** [analog-substance/arsenic#48]
On an engagement with only IPs in scope, when a reverse lookup (or certificate lookup, etc) is done, the domainis not added to a the hostname file  so that gobuster and other tools can be run against the domain.  Different data can be found when running against a domain vs an IP.

**Comment by defektive** [comment]
I think this is a wierd edge case. The DNS enumeration/discovery will ensure that domains are in scope. if you dont have any scope domains, how do we know a domain is in scope? I think in the cases where you only have IPs supplied as scope, you need to run the ip discovery scripts, determine what domains are in scope, add them to scope-domains.txt. then run `arsenic discover`. I know this isn't an ideal solution. The alternative would enable scanning of out of scope domains.
